name: CosmoCargo CI

on:
  push:
  workflow_dispatch:

jobs:

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Backend - Restore dependencies
        run: dotnet restore ./backend

      - name: Backend - Build
        run: dotnet build ./backend --no-restore

      - name: Backend - Test
        run: dotnet test ./backend --no-build --verbosity normal

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Frontend - Install dependencies
        working-directory: ./frontend
        run: npm ci --include=dev

      - name: Frontend - Lint
        working-directory: ./frontend
        run: npm run lint

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: docker-compose -f infrastructure/docker-compose.yml build
